### ISSUE TITLE
How to use additional data types?

### ISSUE THREAD

**Issue by mlehman** [mmcgrana/clj-json#1]
Is there a method to add new data types? The ability to add new types (such as dates) to the multimethod clojure.contrib print-json allows nice flexibility.

**Comment by mmcgrana** [comment]
There is no method to add new data types, and I don't plan to implement such a feature myself. The library is designed specifically to be very fast for basic JSON; if you need custom parsing/unparsing, you might be better off with one of the other JSON libs. I would also consider a pull request for custom parsing/unparsing in clj-json if it did not compromise performance in the basic case.

**Comment by mlehman** [comment]
Yeah, the primary data type lacking in json is a date. I don't really see a standard practice for dates in json yet either.  Just calling toString on objects as a default case might be nice.
