### ISSUE TITLE
Performance problem (clj-json could be nearly 10x faster)

### ISSUE THREAD

**Issue by jwr** [mmcgrana/clj-json#11]
Hi,

Since clojure.data.json is a big performance problem in our app (nearly 30% of request servicing time), I decided to try clj-json. Unfortunately, it isn't much of an improvement, and all because of a tiny issue. On our data, the "coerce" stage constitutes over 91% of cpu time spent in clj-json!

Since we actually do not need any coercing at all, I tested a variant of generate-string with the call to coerce removed. We get excellent performance that way.

Oh, and before you ask - this is a search engine and every millisecond counts. We really _do_ care about performance.

Please provide a fast variant of generate-string for those of us who do not need any fancy conversions. I would submit a pull request, but it's a really simple fix, I can think of several ways this can be implemented and I think it is up to the library author to decide.

thanks,
--J.

**Comment by lancepantz** [comment]
Jan, 
Thanks for the heads up! That's a recent addition, I had no idea it was that detrimental to performance. clj-json is intended to be highly performant, I'll make fixing this a high priority. 
I suspect it's the postwalk. 
Thanks again!
-lance

**Comment by jwr** [comment]
Yes, it's the postwalk — and in our case we'd like to have a way to short-circuit it completely. When generating JSON replies we need to be as fast as possible and we only use a subset of JSON anyway.

Thanks and I'll be waiting for a clojars release so that we can use it!

**Comment by lancepantz** [comment]
Hi Jan,  
I just released version 0.4.1 to clojars, removing the post walk. Let me know how it performs for you.
-lance

**Comment by jwr** [comment]
Hi,

0.4.1 works great. I haven't tried any coercions, though — so I can't comment on how those perform. But in our case we only need the fast path and that works great now.

Thanks for the quick response!

--J.

**Comment by lancepantz** [comment]
Great to hear! I also pushed 0.4.2 a little later with performant support for anything that implements the Iterator interface. That probably eliminates most of the need for coercions.  

Thanks again for the notice,
lance
