### ISSUE TITLE
Failed compile-java

### ISSUE THREAD

**Issue by jaor** [mmcgrana/clj-json#2]
With a fresh checkout and a lein snapshot, `lein deps` runs fine, but `lein compile-java` fails with an exception whose stack trace begins with:

```
Exception in thread "main" java.lang.Exception: Unable to resolve symbol: make-path in this context (compile_java.clj:10)
        at clojure.lang.Compiler.analyze(Compiler.java:5200)
```

**Comment by mmcgrana** [comment]
Still works for me locally, so it must be an environment difference. What is the output of `lein -v` for you?

**Comment by jaor** [comment]
Leiningen 1.2.0-RC2 on Java 1.6.0_20 Java HotSpot(TM) Client VM

(on a Debian machine)

**Comment by mmcgrana** [comment]
Yep, if I try to use 1.2.0-RC2 locally I get the same problem. I'll look into a workaround when I have the chance.

**Comment by mmcgrana** [comment]
Fixed in http://github.com/mmcgrana/clj-json/commit/840ed6fd27b75db86b96a8b18f00dd264cfdd741 by depending on updated lein-javac http://github.com/antoniogarrote/lein-javac/commit/e24268a010f547df01ee144a0ba7c437351c119d.
