### ISSUE TITLE
Something wrong with v0.5.2

### ISSUE THREAD

**Issue by davidwclin** [mmcgrana/clj-json#21]
I created a barebones project depending only on clj-json 0.5.2 and clojure 1.4. Running a script which requires clj-json fails. Problem goes away with v0.5.1.

**Comment by jasapp** [comment]
I've noticed the same thing. Using or requiring clj-json fails with the "not found on classpath" error. Switching to 0.5.1 fixes this.

**Comment by bowsersenior** [comment]
Just ran into the same issue...

**Comment by w01fe** [comment]
Ditto.  It looks like the Clojure src is in the wrong location inside the jar...

**Comment by mkolodziej** [comment]
Same here! Spent an hour on this before finding this issue report...

**Comment by ghost** [comment]
I fixed this by clone it directly from Github and build it by myself. Finally replace it in your local maven repo. This work for me.

**Comment by lancepantz** [comment]
Sorry about that fellas, I just released 0.5.3 to clojars if you'd like to give it a shot

**Comment by ghost** [comment]
OK it works fine now.
